name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: build
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Build env file
      run: |
        export CIRCLE_BRANCH="${GITHUB_REF##*/}"
        make version
        if [[ "$CIRCLE_BRANCH" == "release" ]]; then
          export PACKAGECLOUD_REPOSITORY=dokku/dokku
          make .env.docker
        fi
    - name: Prepare build env
      run: CIRCLE_BRANCH="${GITHUB_REF##*/}" make circleci
    - name: Create build image
      run: CIRCLE_BRANCH="${GITHUB_REF##*/}" make build-docker-image
    - name: Build binary
      run: |
        export CIRCLE_BRANCH="${GITHUB_REF##*/}"
        make build-in-docker
    - name: Run tests
      run: |
        make validate-in-docker
        build/linux/plugn version
    - name: Run sudo test
      run: |
        useradd user
        cp build/linux/plugn user-plugn
        sudo -u user -E -H user-plugn version
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
    - name: Release artifacts
      run: |
        export CIRCLE_BRANCH="${GITHUB_REF##*/}"
        if [[ "$CIRCLE_BRANCH" == "release" ]]; then
          make release-in-docker release-packagecloud-in-docker
        fi
